[build]
  publish = "public"
  command = "npm install --package-lock-only && npm install"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
